name: quill_web_editor_example
description: Example application demonstrating the Quill Web Editor package.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  quill_web_editor:
    path: ../
  google_fonts: ^6.2.1
  pointer_interceptor: ^0.10.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

