name: quill_web_editor_example
description: Example application demonstrating the Quill Web Editor package.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  quill_web_editor:
    path: ../
  google_fonts: 6.1.0
  pointer_interceptor: ^0.10.1+2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
    # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
  
  fonts:
    - family: 'Mulish'
      fonts:
        - asset: assets/fonts/Mulish-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Mulish-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/Mulish-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish-Italic.ttf
          style: italic
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Mulish-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Mulish-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Mulish-Black.ttf
          weight: 900
        - asset: assets/fonts/Mulish-BlackItalic.ttf
          weight: 900
          style: italic

